#!/bin/bash

if ! which gem 2>&1 >/dev/null ; then
  echo "You'll need Ruby installed to build the presentation!"
  echo "See: https://www.ruby-lang.org/en/installation/"
  exit 1
fi

gem install mdpress

if ! which rbenv 2>&1 >/dev/null ; then
  rbenv rehash
fi
